@PROJECT_HASH = tbzuopynwq

###

curl --request GET \
  --url https://lab-08-get-customers-svc-682537251805.us-central1.run.app/getcustomers \
  --header 'content-type: application/json' \
  --header 'user-agent: vscode-restclient'
